version: '2'

services:
  admininmuebles:
    image: adminmuebles
    build:
      context: .
    environment:
       - "PORT=5000"
    ports:
       - "${PORT}:5000"
    mem_limit: 512m
    mem_reservation: 256m