// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  defaultLanguage: 'es',
  baseUrl: 'https://admin-inmuebles-dev.herokuapp.com/', // hardcoded for the moment to target stable dev api
// tslint:disable-next-line: max-line-length
  authenticatedUserToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjBCODAxMUJFN0U2OEY0QzA4MkEwODA3MTkzQjU2N0EyQzlBNjJBNUYiLCJ4NXQiOiJDNEFSdm41bzlNQ0NvSUJ4azdWbm9zbW1LbDgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJBZG1Jbm11ZWJsZXMuRGV2ZWxvcG1lbnQiLCJlbWFpbCI6ImpvcmdlQGphbXRlY2guY2wiLCJuYW1lIjoiam9yZ2VAamFtdGVjaC5jbCIsImRhdGEiOiJ7XCJSdXRcIjowLFwiTWFpbFwiOlwiam9yZ2VAamFtdGVjaC5jbFwiLFwiTm9tYnJlXCI6XCJqb3JnZUBqYW10ZWNoLmNsXCIsXCJUaXBvXCI6MixcIkVzdGFkb1wiOjEsXCJJY29ub1wiOlwiXCIsXCJQYXNzd29yZFwiOm51bGwsXCJDb25kb3NcIjpbe1wiUnV0XCI6MCxcIlJhem9uU29jaWFsXCI6XCJDT05ET01JTklPIEFOVEFSRVMgREUgTEEgTFVaXCIsXCJUaXBvXCI6MSxcIlZpZ2VuY2lhXCI6MSxcIkNyZWF0ZWRCeVwiOm51bGwsXCJDcmVhdGVkT25cIjpcIjAwMDEtMDEtMDFUMDA6MDA6MDBcIixcIlVwZGF0ZWRCeVwiOm51bGwsXCJVcGRhdGVkT25cIjpcIjAwMDEtMDEtMDFUMDA6MDA6MDBcIixcIkF0dHJpYnV0ZXNcIjp7XCJLZXlcIjpudWxsLFwiVmFsdWVcIjpudWxsfX0se1wiUnV0XCI6MCxcIlJhem9uU29jaWFsXCI6XCJFRElGSUNJTyBET04gUVVJSk9URVwiLFwiVGlwb1wiOjEsXCJWaWdlbmNpYVwiOjEsXCJDcmVhdGVkQnlcIjpudWxsLFwiQ3JlYXRlZE9uXCI6XCIwMDAxLTAxLTAxVDAwOjAwOjAwXCIsXCJVcGRhdGVkQnlcIjpudWxsLFwiVXBkYXRlZE9uXCI6XCIwMDAxLTAxLTAxVDAwOjAwOjAwXCIsXCJBdHRyaWJ1dGVzXCI6e1wiS2V5XCI6bnVsbCxcIlZhbHVlXCI6bnVsbH19LHtcIlJ1dFwiOjAsXCJSYXpvblNvY2lhbFwiOlwiQ09ORE9NSU5JTyBCTE9RVUVBRE9cIixcIlRpcG9cIjoxLFwiVmlnZW5jaWFcIjoyLFwiQ3JlYXRlZEJ5XCI6bnVsbCxcIkNyZWF0ZWRPblwiOlwiMDAwMS0wMS0wMVQwMDowMDowMFwiLFwiVXBkYXRlZEJ5XCI6bnVsbCxcIlVwZGF0ZWRPblwiOlwiMDAwMS0wMS0wMVQwMDowMDowMFwiLFwiQXR0cmlidXRlc1wiOntcIktleVwiOm51bGwsXCJWYWx1ZVwiOm51bGx9fV0sXCJDcmVhdGVkQnlcIjpudWxsLFwiQ3JlYXRlZE9uXCI6XCIwMDAxLTAxLTAxVDAwOjAwOjAwXCIsXCJVcGRhdGVkQnlcIjpudWxsLFwiVXBkYXRlZE9uXCI6XCIwMDAxLTAxLTAxVDAwOjAwOjAwXCIsXCJBdHRyaWJ1dGVzXCI6e1wiS2V5XCI6bnVsbCxcIlZhbHVlXCI6bnVsbH19IiwiZXhwIjoxNTYyMzk2MTA5fQ.uewuLt-0a9ZZ5zsvoXlVORWuxrI_yzRECXZ_lcyEK6RSdYAj70MuMqqXjSuVlL8owhP4jWBb8Fwv2e8E1_hSzAzIcgbRqI1Y0_3QsXw5vfzO3oQM_GrLqHaGbkHROrKidosPXnvjM4ktykGnWNoSv2lg0FJYSM6Vh6mgxY55Rqp8sbubMhbqrKJ6R_Kj_8bz7d5RyGoko6p3KSlWBYKD-IIj_A5VpDqundgzWdUctxd_rpLyYcpeC9sq1NhwYYAxIk4qZk_aYZrhtJ5y-Tao7zOFGmya95HEOxtehWUbAWh2UqQN2KonBolL5w6FK1OaKq43CyHpcMDyyvAX-RW9cQ'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
